# .streamlit/secrets.toml

SUPABASE_URL=https://txpgihyqyaixdxcirvqx.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cGdpaHlxeWFpeGR4Y2lydnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDY2OTQsImV4cCI6MjA3NjE4MjY5NH0.16UKuGTS-_wD62lWJW7L9uYP_5Egc3woXRmjUzOGaK8

